### ISSUE TITLE
Updates needed for 2023

### ISSUE THREAD

**Issue by adjavon** [dlmbl/knowledge_extraction#1]
- [x] Standardize whether to use “Task” or “Exercise”
- [ ]  Remove training of the VGG classifier. Instead load the model and do evaluation (and use the extra space to give more details). Alternatively,  give them a link to a script to train their own model if they choose to.
- [x] For Exercise 1.4, no good reason to have two methods here, just do one
- [x]  Make questions tasks: have them discuss in Element/Matrix
- [x] Exercise 2: typo in attributions
- [x] Goes from 2.1 to 2.3
- [x] Exercise 2.1: remove hints! (too obvious) “read the docs”, hint to number of lines (2)
- [ ] Part 3: add more links to everything in the explanation, e.g. the lecture slides (CycleGAN, counterfactual explanation)
- [x] remove exercise 3.1:  It is more about data wrangling than about actual training. We could make this available to them.
- [x] Exercise 3.2: Options good!  Add the numbers from the top to the choices in the code
- [ ] Checkpoint 3: Add learning objectives
- [ ] Memory errors is a problem. Perhaps we should just have a smaller dataset, or smaller models.
- [x]  Remove exercise 4.2
- [x]  Move the TODOs inside the blue boxes.
- [x]  Part 4 is all called 5 for some reason

**Comment by xuefei-wang** [comment]
- [ ] Task 1.2 has a solution block in exercise.ipynb
- [ ] Task 1.2 print statement missing 's': prediction --> predictions, groundtruth --> groundtruths
- [ ] Task 2.3 need to add this line: `attributions_random = (attributions_random.cpu().numpy())`
- [ ] Same as above for task 2.4
- [ ] Task 5.1: this code snippet exists in solution but not exercise: 
```
# Create datasets with only the successes
cf_success_ds = Subset(ds_counterfactual, success)
real_success_ds = Subset(ds_real, success)
```
- [ ] Maybe add a plotting option to the Task 5.2 widget as well?
